# Class Work:
    1. Find the Country Index with maximum gold
    2. Print country with maximum gold
    3. Find the countries with more than 20 gold medals 
    4. Evaluate the dataset and print the medal:
        1. print each country name with number of gold medals
        2. print each country name with total number of medals 

In [1]:
import numpy as np 

#dataset 
np_olympic_country = np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_country_gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_silver = np.array([17,28,25,28,8,14,11])
np_olympic_country_bronze = np.array([19,22,32,29,7,17,14])

In [2]:
# Task 1: Find the Country Index with maximum gold
max_gold_index = np.argmax(np_olympic_country_gold)

In [3]:
# Task 2: Print country with maximum gold
country_with_max_gold = np_olympic_country[max_gold_index]
print("Country with maximum gold:", country_with_max_gold)

Country with maximum gold: US


In [7]:
# Task 3: Find the countries with more than 20 gold medals
countries_with_more_than_20_gold = np_olympic_country[np_olympic_country_gold > 20]
print("Country with more than 20 gold medals: ", countries_with_more_than_20_gold)

Country with more than 20 gold medals:  ['GBR' 'China' 'RUS' 'US']


In [5]:
# Task 4: Evaluate the dataset and print the medals
# Task 4.1: Print each country name with the number of gold medals
for country, gold_medals in zip(np_olympic_country, np_olympic_country_gold):
    print(f"{country} - Gold Medals: {gold_medals}")

GBR - Gold Medals: 29
China - Gold Medals: 38
RUS - Gold Medals: 24
US - Gold Medals: 46
KOR - Gold Medals: 13
JPN - Gold Medals: 7
GER - Gold Medals: 11


In [6]:
# Task 4.2: Print each country name with the total number of medals
total_medals = np_olympic_country_gold + np_olympic_country_silver + np_olympic_country_bronze
for country, total in zip(np_olympic_country, total_medals):
    print(f"{country} - Total Medals: {total}")

GBR - Total Medals: 65
China - Total Medals: 88
RUS - Total Medals: 81
US - Total Medals: 103
KOR - Total Medals: 28
JPN - Total Medals: 38
GER - Total Medals: 36


# 1. Create a 3X3X3 array with random values

In [19]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.74854358 0.98126263 0.80270247]
  [0.80651453 0.05721695 0.43934571]
  [0.77552357 0.34707513 0.07184017]]

 [[0.12297597 0.61867157 0.74480063]
  [0.07150005 0.98940923 0.83503516]
  [0.98753582 0.53107696 0.43541267]]

 [[0.77114527 0.58779316 0.39375895]
  [0.60228117 0.32535759 0.56553381]
  [0.2703836  0.54756861 0.01289297]]]


# 2. Create a 5X5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill the values 1, 2, 3, 4 just below the diagonal
for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3. Create a 8X8 matrix and fill it with a checkboard pattern

In [7]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8))

# Fill the checkerboard pattern
matrix[1::2, ::2] = 1  # Set every second row, starting from the second row, with even columns to 1
matrix[::2, 1::2] = 1  # Set every second row, starting from the first row, with odd columns to 1

print(matrix)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5X5 random matrix

In [21]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the matrix
mean = random_matrix.mean()
std_dev = random_matrix.std()

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Random Matrix:
[[0.05999737 0.44778861 0.9721211  0.23358148 0.10635276]
 [0.41892828 0.37329367 0.05835063 0.52000555 0.24671945]
 [0.69057036 0.51811231 0.10703166 0.79797338 0.31025638]
 [0.70395075 0.97982259 0.86744552 0.71980647 0.04603691]
 [0.43980851 0.34712659 0.77543223 0.97897669 0.3316403 ]]

Normalized Matrix:
[[-1.40462536 -0.11400994  1.63103097 -0.82691676 -1.25034908]
 [-0.21006057 -0.36193798 -1.4101059   0.12633661 -0.78319204]
 [ 0.6939966   0.12003569 -1.24808962  1.05144663 -0.57173356]
 [ 0.73852812  1.65666247  1.2826582   0.79129785 -1.45108742]
 [-0.14056865 -0.44902511  0.97642701  1.65384721 -0.50056534]]


# 5. How to find common values between two arrays? 

In [9]:
import numpy as np

# Define two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values using NumPy's intersect1d function
common_values = np.intersect1d(array1, array2)

print(common_values)

[3 4 5]


# 6. How to get the dates of yesterday,today and tomorrow?

In [10]:
import numpy as np
from datetime import datetime, timedelta

# Get the current date (today)
today = datetime.now().date()

# Calculate the date for yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Convert the dates to NumPy datetime64 objects
today_np = np.datetime64(today)
yesterday_np = np.datetime64(yesterday)
tomorrow_np = np.datetime64(tomorrow)

print("Yesterday (NumPy):", yesterday_np)
print("Today (NumPy):", today_np)
print("Tomorrow (NumPy):", tomorrow_np)

Yesterday (NumPy): 2023-09-20
Today (NumPy): 2023-09-21
Tomorrow (NumPy): 2023-09-22


# 7. Consider two random array A and B, check if they are equal?

In [12]:
import numpy as np

# Generate two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

print(A)
print()
print(B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


[0.75742713 0.68002344 0.45211165 0.79515587 0.04081548]

[0.21815486 0.60106792 0.0491484  0.16290358 0.72805702]
Arrays A and B are not equal.


# 8. Create random vector of size 10 and replace the maximum value by 0

In [15]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

#print vector before replacing
print(random_vector)
print()

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector with Max Value Replaced:")
print()
print(random_vector)


[0.60642311 0.87053607 0.68754675 0.92474522 0.31255732 0.49541886
 0.2842577  0.26492947 0.10378975 0.98706998]

Random Vector with Max Value Replaced:

[0.60642311 0.87053607 0.68754675 0.92474522 0.31255732 0.49541886
 0.2842577  0.26492947 0.10378975 0.        ]


# 9. How to print all the values of an array?

In [16]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

for element in my_array:
    print(element)


1
2
3
4
5


# 10. Subtract the mean of each row of matrix

In [17]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1)

# Subtract the row means from the corresponding rows
normalized_matrix = matrix - row_means[:, np.newaxis]

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11. Consider a given vector, how to add 'a' to each element indexed by a second vector(be careful with repeated indices)?

In [27]:
import numpy as np

# Given vector
original_vector = np.array([1, 2, 3, 4, 5])

# Second vector with indices (assuming indices are unique)
indices = np.array([0,1,2,3,4])

# Value to add
a = 10

# Create a copy of the original vector to avoid modifying it
result_vector = original_vector.copy()

# Add 'a' to elements at the specified indices
result_vector[indices] += a

print("Original Vector:", original_vector)
print("Result Vector:", result_vector)


Original Vector: [1 2 3 4 5]
Result Vector: [11 12 13 14 15]


# 12. How to get the diagnoal of a dot product?

In [28]:
import numpy as np

# Define two matrices
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Compute the dot product
dot_product_result = np.dot(matrix_A, matrix_B)

# Extract the diagonal elements
diagonal_elements = np.diag(dot_product_result)

print("Dot Product Result:")
print(dot_product_result)
print("\nDiagonal Elements:")
print(diagonal_elements)

Dot Product Result:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal Elements:
[30 69 90]


# 13. How to find the most frequent value in an array

In [30]:
import numpy as np

x = np.random.randint(0,10,50)
x

array([4, 1, 5, 1, 4, 5, 3, 8, 3, 4, 1, 1, 3, 5, 4, 3, 7, 4, 0, 9, 2, 5,
       4, 6, 2, 6, 6, 1, 9, 8, 2, 1, 3, 2, 5, 7, 8, 4, 7, 5, 9, 7, 6, 4,
       2, 7, 7, 6, 1, 5])

In [31]:
# Use numpy's unique function to get unique values and their counts
unique_values, counts = np.unique(x, return_counts=True)

# Find the most frequent element and its count
most_common_element = unique_values[np.argmax(counts)]
count = np.max(counts)

print(f"The most frequent value is {most_common_element} with a count of {count}.")


The most frequent value is 4 with a count of 8.


# 14. How to get the n largest values of an array

In [36]:
import numpy as np

# Define array
my_array = np.array([4, 2, 8, 1, 6, 5, 7, 3])

# Specify the value of 'n' for the largest values you want
n = 3

# Get the 'n' largest values using numpy's argsort
largest_indices = np.argsort(my_array)[-n:]
largest_values = my_array[largest_indices]

print(f"The {n} largest values are: {largest_values}")


The 3 largest values are: [6 7 8]


# 15. How to create a record array from a regular array?

In [38]:
import numpy as np

# Create a regular array (or list of tuples)
regular_array = [(1, "Manthan", 23),
                 (2, "Mayoor", 22),
                 (3, "Shamal", 25)]

# Define the data types and field names
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

# Create a record array from the regular array
record_array = np.rec.array(regular_array, dtype=dtype)

# Access elements by field name
print("Record Array:")
print(record_array)
print("\nAccessing by Field Name:")
print("ID:", record_array['ID'])
print("Name:", record_array['Name'])
print("Age:", record_array['Age'])


Record Array:
[(1, 'Manthan', 23) (2, 'Mayoor', 22) (3, 'Shamal', 25)]

Accessing by Field Name:
ID: [1 2 3]
Name: ['Manthan' 'Mayoor' 'Shamal']
Age: [23 22 25]


# 16. How to swap two rows of an array?

In [39]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Define the indices of the rows you want to swap
row1_index = 0  # Index of the first row
row2_index = 2  # Index of the second row

# Swap the rows
temp_row = np.copy(array[row1_index, :])  # Create a copy of the first row
array[row1_index, :] = array[row2_index, :]  # Replace the first row with the second row
array[row2_index, :] = temp_row  # Replace the second row with the copy of the first row

print("Array with Rows Swapped:")
print(array)


Array with Rows Swapped:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write a python code to reshape to the next dimension of numpy array?

In [40]:
import numpy as np

x = np.array([[23,34,121],[23,22,67],[686,434,123]])
x

array([[ 23,  34, 121],
       [ 23,  22,  67],
       [686, 434, 123]])

In [43]:
import numpy as np

x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])

# Reshape the 2D array into a 3D array with one additional dimension
reshaped_x = x.reshape((x.shape[0], x.shape[1],1))

print("Original 2D Array:")
print(x)
print("\nReshaped 3D Array:")
print(reshaped_x)


Original 2D Array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped 3D Array:
[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]
